language: c
script: make clean && make && make test && make clean && make coverage
compiler:
  - clang
  - gcc
sudo: false
before_install:
  - export "PATH=$HOME/.local/bin:$PATH"
  - pip install --user cpp-coveralls
after_success:
  - coveralls --gcov-options '\-lp'
